import type {
  PracticePlan,
  ProgressSummary,
  ScoreSheet,
  SessionRecap,
  StudentProfile,
  TeacherDashboardStudent,
  TeacherMessage,
} from "./domain";

export const mockStudentProfile: StudentProfile = {
  id: "student-demo",
  displayName: "Jeremy",
  instrument: "viola",
  level: "beginner",
  weeklyPracticeGoalMinutes: 120,
  currentFocus: ["Alto clef reading", "Open string tone", "Steady counting"],
};

export const mockPracticePlan: PracticePlan = {
  id: "plan-today",
  dateLabel: "Today",
  headline: "Build a steadier tone and cleaner note reading",
  targetMinutes: 25,
  exercises: [
    {
      id: "open-string-tone",
      title: "Open String Tone Ladder",
      category: "warmup",
      minutes: 5,
      description: "Play C, G, D, and A strings with long bows and consistent volume.",
      focusMetric: "tone",
    },
    {
      id: "alto-clef-notes",
      title: "Alto Clef Quick Read",
      category: "theory",
      minutes: 5,
      description: "Name and play notes around middle C without looking at finger labels.",
      focusMetric: "reading",
    },
    {
      id: "quarter-note-pulse",
      title: "Quarter Note Pulse",
      category: "rhythm",
      minutes: 6,
      description: "Tap and play quarter notes at 72 BPM with a metronome.",
      focusMetric: "rhythm",
    },
    {
      id: "first-scale",
      title: "D Major Starter Scale",
      category: "technique",
      minutes: 9,
      description: "Practice D major in one octave, pausing on any note that sounds sharp or flat.",
      focusMetric: "pitch",
    },
  ],
};

export const mockProgressSummary: ProgressSummary = {
  streakDays: 5,
  weeklyMinutes: 86,
  pitchAccuracy: 78,
  rhythmAccuracy: 84,
  completedSessions: 12,
  strongestSkill: "Rhythm consistency",
  nextFocus: "D string intonation",
};

export const mockScoreSheets: ScoreSheet[] = [
  {
    id: "score-d-major-study",
    title: "D Major Starter Study",
    composer: "Viola Method",
    level: "beginner",
    keySignature: "D major",
    timeSignature: "4/4",
    tempoMarking: "Quarter = 72",
    tempoBpm: 72,
    source: "teacher_assigned",
    status: "learning",
    assignedFocus: ["First finger placement", "Even quarter notes", "Open D resonance"],
    lastPracticedLabel: "Today",
    practiceMinutes: 18,
    measuresToReview: "Measures 5-8",
    teacherNote: "Keep the bow closer to the bridge on the long notes and listen for ringing D string resonance.",
    notes: [
      { id: "dm-1-1", measure: 1, pitch: "D", duration: "quarter", octave: 4, bowing: "down-bow", stringName: "D" },
      { id: "dm-1-2", measure: 1, pitch: "E", duration: "quarter", octave: 4, bowing: "up-bow", stringName: "D" },
      { id: "dm-1-3", measure: 1, pitch: "F#", duration: "quarter", octave: 4, articulation: "tenuto", stringName: "D" },
      { id: "dm-1-4", measure: 1, pitch: "G", duration: "quarter", octave: 4, stringName: "D" },
      { id: "dm-2-1", measure: 2, pitch: "A", duration: "half", octave: 4, bowing: "down-bow", stringName: "A" },
      { id: "dm-2-2", measure: 2, pitch: "Rest", duration: "quarter" },
      { id: "dm-2-3", measure: 2, pitch: "A", duration: "quarter", octave: 4, bowing: "up-bow", stringName: "A" },
    ],
  },
  {
    id: "score-alto-clef-lines",
    title: "Alto Clef Line Builder",
    composer: "Reading Lab",
    level: "beginner",
    keySignature: "C major",
    timeSignature: "3/4",
    tempoMarking: "Quarter = 66",
    tempoBpm: 66,
    source: "teacher_assigned",
    status: "new",
    assignedFocus: ["Middle C anchor", "Stepwise reading", "Note naming before playing"],
    lastPracticedLabel: "Not started",
    practiceMinutes: 0,
    measuresToReview: "Lines 1-2",
    teacherNote: "Say each note name out loud before playing so the visual pattern becomes automatic.",
    notes: [
      { id: "ac-1-1", measure: 1, pitch: "C", duration: "quarter", octave: 4, stringName: "G" },
      { id: "ac-1-2", measure: 1, pitch: "D", duration: "quarter", octave: 4, stringName: "D" },
      { id: "ac-1-3", measure: 1, pitch: "E", duration: "quarter", octave: 4, stringName: "D" },
      { id: "ac-2-1", measure: 2, pitch: "F", duration: "quarter", octave: 4, articulation: "separate", stringName: "D" },
      { id: "ac-2-2", measure: 2, pitch: "Rest", duration: "quarter" },
      { id: "ac-2-3", measure: 2, pitch: "G", duration: "quarter", octave: 4, stringName: "D" },
    ],
  },
  {
    id: "score-c-string-warmup",
    title: "C String Resonance Warmup",
    composer: "Tone Lab",
    level: "early-intermediate",
    keySignature: "F major",
    timeSignature: "4/4",
    tempoMarking: "Quarter = 60",
    tempoBpm: 60,
    source: "teacher_assigned",
    status: "polishing",
    assignedFocus: ["Bow weight", "Relaxed left hand", "Slow string crossings"],
    lastPracticedLabel: "Yesterday",
    practiceMinutes: 24,
    measuresToReview: "Measures 9-12",
    teacherNote: "Let the arm weight settle into the string before moving the bow. Avoid pressing with the index finger.",
    notes: [
      { id: "cs-1-1", measure: 1, pitch: "C", duration: "half", octave: 3, bowing: "down-bow", stringName: "C" },
      { id: "cs-1-2", measure: 1, pitch: "F", duration: "half", octave: 3, bowing: "up-bow", stringName: "C" },
      { id: "cs-2-1", measure: 2, pitch: "G", duration: "quarter", octave: 3, articulation: "tenuto", stringName: "C" },
      { id: "cs-2-2", measure: 2, pitch: "A", duration: "quarter", octave: 3, bowing: "slur", stringName: "G" },
      { id: "cs-2-3", measure: 2, pitch: "Bb", duration: "quarter", octave: 3, bowing: "slur", stringName: "G" },
      { id: "cs-2-4", measure: 2, pitch: "C", duration: "quarter", octave: 4, stringName: "G" },
    ],
  },
  {
    id: "score-minuet-theme",
    title: "Minuet Theme",
    composer: "Classical Excerpt",
    level: "early-intermediate",
    keySignature: "G major",
    timeSignature: "3/4",
    tempoMarking: "Quarter = 84",
    tempoBpm: 84,
    source: "teacher_assigned",
    status: "performance-ready",
    assignedFocus: ["Phrase shape", "Light bow lift", "Clean final cadence"],
    lastPracticedLabel: "Saturday",
    practiceMinutes: 42,
    measuresToReview: "Final 8 measures",
    teacherNote: "This is close to performance ready. Keep the second phrase lighter and save bow for the cadence.",
    notes: [
      { id: "mt-1-1", measure: 1, pitch: "G", duration: "quarter", octave: 4, bowing: "down-bow", stringName: "D" },
      { id: "mt-1-2", measure: 1, pitch: "B", duration: "quarter", octave: 4, articulation: "light", stringName: "A" },
      { id: "mt-1-3", measure: 1, pitch: "D", duration: "quarter", octave: 5, bowing: "up-bow", stringName: "A" },
      { id: "mt-2-1", measure: 2, pitch: "C", duration: "quarter", octave: 5, bowing: "slur", stringName: "A" },
      { id: "mt-2-2", measure: 2, pitch: "B", duration: "quarter", octave: 4, bowing: "slur", stringName: "A" },
      { id: "mt-2-3", measure: 2, pitch: "A", duration: "quarter", octave: 4, articulation: "lift", stringName: "A" },
    ],
  },
];

export const mockTeacherMessages: TeacherMessage[] = [
  {
    id: "teacher-1",
    role: "teacher",
    content: "Today we are keeping the session focused: steady bow, clear alto clef notes, and one scale played slowly enough to hear every pitch.",
  },
  {
    id: "student-1",
    role: "student",
    content: "I keep mixing up C and E in alto clef.",
  },
  {
    id: "teacher-2",
    role: "teacher",
    content: "Good catch. Anchor middle C on the center line first, then count by steps. Do five slow reads before you touch the instrument.",
  },
];

export const mockSessionRecaps: SessionRecap[] = [
  {
    id: "recap-1",
    title: "Tone and pulse",
    dateLabel: "Yesterday",
    summary: "Your pulse stayed consistent through the open string exercise, and the D string notes were more centered by the final take.",
    wins: ["Held tempo at 72 BPM", "Cleaner long bows", "Fewer note-name hesitations"],
    nextSteps: ["Repeat D major slowly", "Spend two minutes on C/E recognition"],
  },
  {
    id: "recap-2",
    title: "Reading check",
    dateLabel: "Saturday",
    summary: "Alto clef reading is getting faster, especially around middle C. Lower notes still need slower counting.",
    wins: ["Improved note naming", "Good posture reminders"],
    nextSteps: ["Review notes below middle C", "Keep bow speed even"],
  },
];

export const mockTeacherDashboardStudents: TeacherDashboardStudent[] = [
  {
    id: "student-demo",
    studentName: "Jeremy Muniz",
    assignedPracticePlan: "Build a steadier tone and cleaner note reading",
    weeklyPracticeMinutes: 86,
    completedExercises: ["Open String Tone Ladder", "Alto Clef Quick Read", "Quarter Note Pulse"],
    recentSessionSummary:
      "Jeremy held tempo more consistently through the rhythm drill and showed cleaner long-bow control on open strings.",
    teacherNotes: [
      "Keep D major slow enough to hear each pitch settle.",
      "Ask for one clean take before moving tempo higher.",
      "Review C/E recognition in alto clef at the start of each session.",
    ],
    nextFocusArea: "D string intonation and relaxed bow changes",
    reviewStatus: "needs-review",
  },
  {
    id: "student-maya",
    studentName: "Maya Chen",
    assignedPracticePlan: "Improve alto clef fluency and C string response",
    weeklyPracticeMinutes: 112,
    completedExercises: ["C String Resonance Builder", "Alto Clef Lower Notes", "Slow Bow Reset"],
    recentSessionSummary:
      "Maya's lower-string tone is fuller this week, and her note naming below middle C is becoming more automatic.",
    teacherNotes: [
      "Assign two short lower-clef reading checks before repertoire.",
      "Encourage slower bow starts on C string entrances.",
      "Use a drone for first-finger placement in F major.",
    ],
    nextFocusArea: "Lower alto clef reading and C string starts",
    reviewStatus: "ready",
  },
  {
    id: "student-owen",
    studentName: "Owen Rivera",
    assignedPracticePlan: "Prepare clean D major scale and steady quarter-note pulse",
    weeklyPracticeMinutes: 64,
    completedExercises: ["Quarter Note Pulse", "D Major Starter Scale"],
    recentSessionSummary:
      "Owen completed the rhythm work but rushed the final scale take when the tempo increased.",
    teacherNotes: [
      "Keep metronome work at 66 BPM until the scale stays relaxed.",
      "Add one open-string bow warmup before every recorded take.",
      "Praise the improved counting consistency from the last session.",
    ],
    nextFocusArea: "Tempo discipline during scale work",
    reviewStatus: "reviewed",
  },
];
