import type {
  MusicSheet,
  PracticePlan,
  ProgressSummary,
  SessionRecap,
  StudentProfile,
  TeacherDashboardStudent,
  TeacherMessage,
} from "./domain";
import { sampleViolaMusicXml } from "./sampleMusicXml";

export const mockStudentProfile: StudentProfile = {
  id: "student-demo",
  displayName: "Jeremy",
  instrument: "viola",
  level: "beginner",
  weeklyPracticeGoalMinutes: 120,
  currentFocus: ["Alto clef reading", "Open string tone", "Steady counting"],
};

export const mockPracticePlan: PracticePlan = {
  id: "plan-today",
  dateLabel: "Today",
  headline: "Build a steadier tone and cleaner note reading",
  targetMinutes: 25,
  exercises: [
    {
      id: "open-string-tone",
      title: "Open String Tone Ladder",
      category: "warmup",
      minutes: 5,
      description: "Play C, G, D, and A strings with long bows and consistent volume.",
      focusMetric: "tone",
    },
    {
      id: "alto-clef-notes",
      title: "Alto Clef Quick Read",
      category: "theory",
      minutes: 5,
      description: "Name and play notes around middle C without looking at finger labels.",
      focusMetric: "reading",
    },
    {
      id: "quarter-note-pulse",
      title: "Quarter Note Pulse",
      category: "rhythm",
      minutes: 6,
      description: "Tap and play quarter notes at 72 BPM with a metronome.",
      focusMetric: "rhythm",
    },
    {
      id: "first-scale",
      title: "D Major Starter Scale",
      category: "technique",
      minutes: 9,
      description: "Practice D major in one octave, pausing on any note that sounds sharp or flat.",
      focusMetric: "pitch",
    },
  ],
};

export const mockProgressSummary: ProgressSummary = {
  streakDays: 5,
  weeklyMinutes: 86,
  pitchAccuracy: 78,
  rhythmAccuracy: 84,
  completedSessions: 12,
  strongestSkill: "Rhythm consistency",
  nextFocus: "D string intonation",
};

export const mockMusicSheets: MusicSheet[] = [
  {
    id: "sheet-d-major-study",
    title: "D Major Starter Study",
    composer: "Viola Method",
    materialType: "score_sheet",
    instrument: "viola",
    clef: "alto",
    keySignature: "D major",
    timeSignature: "4/4",
    tempoBpm: 72,
    source: "teacher_assigned",
    status: "needs_review",
    createdAt: "2026-07-01",
    updatedAt: "2026-07-04",
    lastPracticedAt: "Today",
    musicXml: sampleViolaMusicXml,
    notes: [
      { id: "dm-1-1", measure: 1, beat: 1, pitch: "D", duration: "quarter", octave: 4, isRest: false, bowing: "down_bow", articulation: "none", stringName: "D", fingering: "0" },
      { id: "dm-1-2", measure: 1, beat: 2, pitch: "E", duration: "quarter", octave: 4, isRest: false, bowing: "up_bow", articulation: "none", stringName: "D", fingering: "1" },
      { id: "dm-1-3", measure: 1, beat: 3, pitch: "F#", duration: "quarter", octave: 4, isRest: false, bowing: "down_bow", articulation: "tenuto", stringName: "D", fingering: "2" },
      { id: "dm-1-4", measure: 1, beat: 4, pitch: "G", duration: "quarter", octave: 4, isRest: false, bowing: "up_bow", articulation: "none", stringName: "D", fingering: "3" },
      { id: "dm-2-1", measure: 2, beat: 1, pitch: "A", duration: "half", octave: 4, isRest: false, bowing: "down_bow", articulation: "arco", stringName: "A" },
      { id: "dm-2-2", measure: 2, beat: 3, duration: "quarter", isRest: true, bowing: "none", articulation: "none" },
      { id: "dm-2-3", measure: 2, beat: 4, pitch: "A", duration: "quarter", octave: 4, isRest: false, bowing: "up_bow", articulation: "accent", stringName: "A" },
    ],
  },
  {
    id: "sheet-alto-clef-lines",
    title: "Alto Clef Line Builder",
    composer: "Reading Lab",
    materialType: "key_change_drill",
    instrument: "viola",
    clef: "alto",
    keySignature: "C major",
    timeSignature: "3/4",
    tempoBpm: 66,
    source: "manual",
    status: "draft",
    createdAt: "2026-07-02",
    updatedAt: "2026-07-03",
    musicXml: sampleViolaMusicXml,
    notes: [
      { id: "ac-1-1", measure: 1, beat: 1, pitch: "C", duration: "quarter", octave: 4, isRest: false, articulation: "none", bowing: "none", stringName: "G" },
      { id: "ac-1-2", measure: 1, beat: 2, pitch: "D", duration: "quarter", octave: 4, isRest: false, articulation: "none", bowing: "none", stringName: "D" },
      { id: "ac-1-3", measure: 1, beat: 3, pitch: "E", duration: "quarter", octave: 4, isRest: false, articulation: "staccato", bowing: "none", stringName: "D" },
      { id: "ac-2-1", measure: 2, beat: 1, pitch: "F", duration: "quarter", octave: 4, isRest: false, articulation: "tenuto", bowing: "none", stringName: "D" },
      { id: "ac-2-2", measure: 2, beat: 2, duration: "quarter", isRest: true, articulation: "none", bowing: "none" },
      { id: "ac-2-3", measure: 2, beat: 3, pitch: "G", duration: "quarter", octave: 4, isRest: false, articulation: "none", bowing: "none", stringName: "D" },
    ],
  },
  {
    id: "sheet-c-string-warmup",
    title: "C String Resonance Warmup",
    composer: "Tone Lab",
    materialType: "warmup",
    instrument: "viola",
    clef: "alto",
    keySignature: "F major",
    timeSignature: "4/4",
    tempoBpm: 60,
    source: "recorded_draft",
    status: "needs_review",
    createdAt: "2026-07-03",
    updatedAt: "2026-07-04",
    lastPracticedAt: "Yesterday",
    musicXml: sampleViolaMusicXml,
    notes: [
      { id: "cs-1-1", measure: 1, beat: 1, pitch: "C", duration: "half", octave: 3, isRest: false, bowing: "down_bow", articulation: "arco", stringName: "C" },
      { id: "cs-1-2", measure: 1, beat: 3, pitch: "F", duration: "half", octave: 3, isRest: false, bowing: "up_bow", articulation: "vibrato", stringName: "C" },
      { id: "cs-2-1", measure: 2, beat: 1, pitch: "G", duration: "quarter", octave: 3, isRest: false, articulation: "tenuto", bowing: "down_bow", stringName: "C" },
      { id: "cs-2-2", measure: 2, beat: 2, pitch: "A", duration: "quarter", octave: 3, isRest: false, bowing: "up_bow", articulation: "slur", stringName: "G" },
      { id: "cs-2-3", measure: 2, beat: 3, pitch: "Bb", duration: "quarter", octave: 3, isRest: false, bowing: "down_bow", articulation: "slur", stringName: "G" },
      { id: "cs-2-4", measure: 2, beat: 4, pitch: "C", duration: "quarter", octave: 4, isRest: false, bowing: "up_bow", articulation: "none", stringName: "G" },
    ],
  },
  {
    id: "sheet-minuet-theme",
    title: "Minuet Theme",
    composer: "Classical Excerpt",
    materialType: "score_sheet",
    instrument: "viola",
    clef: "alto",
    keySignature: "G major",
    timeSignature: "3/4",
    tempoBpm: 84,
    source: "teacher_assigned",
    status: "ready",
    createdAt: "2026-06-29",
    updatedAt: "2026-07-04",
    lastPracticedAt: "Saturday",
    musicXml: sampleViolaMusicXml,
    notes: [
      { id: "mt-1-1", measure: 1, beat: 1, pitch: "G", duration: "quarter", octave: 4, isRest: false, bowing: "down_bow", articulation: "none", stringName: "D" },
      { id: "mt-1-2", measure: 1, beat: 2, pitch: "B", duration: "quarter", octave: 4, isRest: false, articulation: "staccato", bowing: "none", stringName: "A" },
      { id: "mt-1-3", measure: 1, beat: 3, pitch: "D", duration: "quarter", octave: 5, isRest: false, bowing: "up_bow", articulation: "accent", stringName: "A" },
      { id: "mt-2-1", measure: 2, beat: 1, pitch: "C", duration: "quarter", octave: 5, isRest: false, bowing: "none", articulation: "slur", stringName: "A" },
      { id: "mt-2-2", measure: 2, beat: 2, pitch: "B", duration: "quarter", octave: 4, isRest: false, bowing: "none", articulation: "slur", stringName: "A" },
      { id: "mt-2-3", measure: 2, beat: 3, pitch: "A", duration: "quarter", octave: 4, isRest: false, articulation: "tenuto", bowing: "none", stringName: "A" },
    ],
  },
  {
    id: "sheet-open-string-tuning",
    title: "Open String Tuning Check",
    composer: "Tuning Lab",
    materialType: "tuning_exercise",
    instrument: "viola",
    clef: "alto",
    keySignature: "Open strings",
    timeSignature: "4/4",
    tempoBpm: 54,
    source: "teacher_assigned",
    status: "ready",
    createdAt: "2026-07-04",
    updatedAt: "2026-07-04",
    musicXml: sampleViolaMusicXml,
    notes: [
      { id: "tu-1-1", measure: 1, beat: 1, pitch: "C", duration: "half", octave: 3, isRest: false, bowing: "down_bow", articulation: "tenuto", stringName: "C" },
      { id: "tu-1-2", measure: 1, beat: 3, pitch: "G", duration: "half", octave: 3, isRest: false, bowing: "up_bow", articulation: "tenuto", stringName: "G" },
      { id: "tu-2-1", measure: 2, beat: 1, pitch: "D", duration: "half", octave: 4, isRest: false, bowing: "down_bow", articulation: "tenuto", stringName: "D" },
      { id: "tu-2-2", measure: 2, beat: 3, pitch: "A", duration: "half", octave: 4, isRest: false, bowing: "up_bow", articulation: "tenuto", stringName: "A" },
    ],
  },
];

export const mockTeacherMessages: TeacherMessage[] = [
  {
    id: "teacher-1",
    role: "teacher",
    content: "Today we are keeping the session focused: steady bow, clear alto clef notes, and one scale played slowly enough to hear every pitch.",
  },
  {
    id: "student-1",
    role: "student",
    content: "I keep mixing up C and E in alto clef.",
  },
  {
    id: "teacher-2",
    role: "teacher",
    content: "Good catch. Anchor middle C on the center line first, then count by steps. Do five slow reads before you touch the instrument.",
  },
];

export const mockSessionRecaps: SessionRecap[] = [
  {
    id: "recap-1",
    title: "Tone and pulse",
    dateLabel: "Yesterday",
    summary: "Your pulse stayed consistent through the open string exercise, and the D string notes were more centered by the final take.",
    wins: ["Held tempo at 72 BPM", "Cleaner long bows", "Fewer note-name hesitations"],
    nextSteps: ["Repeat D major slowly", "Spend two minutes on C/E recognition"],
  },
  {
    id: "recap-2",
    title: "Reading check",
    dateLabel: "Saturday",
    summary: "Alto clef reading is getting faster, especially around middle C. Lower notes still need slower counting.",
    wins: ["Improved note naming", "Good posture reminders"],
    nextSteps: ["Review notes below middle C", "Keep bow speed even"],
  },
];

export const mockTeacherDashboardStudents: TeacherDashboardStudent[] = [
  {
    id: "student-demo",
    studentName: "Jeremy Muniz",
    assignedPracticePlan: "Build a steadier tone and cleaner note reading",
    weeklyPracticeMinutes: 86,
    completedExercises: ["Open String Tone Ladder", "Alto Clef Quick Read", "Quarter Note Pulse"],
    recentSessionSummary:
      "Jeremy held tempo more consistently through the rhythm drill and showed cleaner long-bow control on open strings.",
    teacherNotes: [
      "Keep D major slow enough to hear each pitch settle.",
      "Ask for one clean take before moving tempo higher.",
      "Review C/E recognition in alto clef at the start of each session.",
    ],
    nextFocusArea: "D string intonation and relaxed bow changes",
    reviewStatus: "needs-review",
  },
  {
    id: "student-maya",
    studentName: "Maya Chen",
    assignedPracticePlan: "Improve alto clef fluency and C string response",
    weeklyPracticeMinutes: 112,
    completedExercises: ["C String Resonance Builder", "Alto Clef Lower Notes", "Slow Bow Reset"],
    recentSessionSummary:
      "Maya's lower-string tone is fuller this week, and her note naming below middle C is becoming more automatic.",
    teacherNotes: [
      "Assign two short lower-clef reading checks before repertoire.",
      "Encourage slower bow starts on C string entrances.",
      "Use a drone for first-finger placement in F major.",
    ],
    nextFocusArea: "Lower alto clef reading and C string starts",
    reviewStatus: "ready",
  },
  {
    id: "student-owen",
    studentName: "Owen Rivera",
    assignedPracticePlan: "Prepare clean D major scale and steady quarter-note pulse",
    weeklyPracticeMinutes: 64,
    completedExercises: ["Quarter Note Pulse", "D Major Starter Scale"],
    recentSessionSummary:
      "Owen completed the rhythm work but rushed the final scale take when the tempo increased.",
    teacherNotes: [
      "Keep metronome work at 66 BPM until the scale stays relaxed.",
      "Add one open-string bow warmup before every recorded take.",
      "Praise the improved counting consistency from the last session.",
    ],
    nextFocusArea: "Tempo discipline during scale work",
    reviewStatus: "reviewed",
  },
];
